name: Build and Deploy Cloud Run

on:
  workflow_dispatch:
# on:
#  push:
#    branches:
#      - main

jobs:
  CloudRun-deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: 'Authenticate to GCP as Infrastructure SA for deployment'
        uses: 'google-github-actions/auth@v1'
        with:
          export_environment_variables: true
          project_id : ${{ vars.PROJECT_ID }}
          workload_identity_provider: ${{ vars.WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ vars.INFRA_SA_EMAIL }}  # Use your Infrastructure SA to manage resources

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}



      - name: Configure Docker
        run: gcloud auth configure-docker us-central1-docker.pkg.dev

      - name: Build and push Docker image
        run: |
          cd App
          docker build -t us-central1-docker.pkg.dev/${{ vars.PROJECT_ID }}/dbvolthacksquad/react-app:$GITHUB_SHA .
          docker push  us-central1-docker.pkg.dev/${{ vars.PROJECT_ID }}/dbvolthacksquad/react-app:$GITHUB_SHA
      

      - name: Cloud Run Deploy
        run: |
          gcloud run deploy tfc-cloud-run-service	 \
          --region us-central1 \
          --image us-central1-docker.pkg.dev/${{ vars.PROJECT_ID }}/dbvolthacksquad/react-app:$GITHUB_SHA \
          --platform "managed" \
          --service-account workload@hack-team-dbvolt-hacksquad.iam.gserviceaccount.com \
          --port 8080 \
          --allow-unauthenticated
